//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBwithStoreproc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MvcDBEntities : DbContext
    {
        public MvcDBEntities()
            : base("name=MvcDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employeeDetail> employeeDetails { get; set; }
    
        public virtual ObjectResult<Sp_GetEmployee_Result> Sp_GetEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetEmployee_Result>("Sp_GetEmployee");
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_insertEmployee(string empname, Nullable<int> salary, string empDesignation)
        {
            var empnameParameter = empname != null ?
                new ObjectParameter("empname", empname) :
                new ObjectParameter("empname", typeof(string));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("salary", salary) :
                new ObjectParameter("salary", typeof(int));
    
            var empDesignationParameter = empDesignation != null ?
                new ObjectParameter("empDesignation", empDesignation) :
                new ObjectParameter("empDesignation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_insertEmployee", empnameParameter, salaryParameter, empDesignationParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_insertEmployeeExample2(string empname, Nullable<int> salary, string empDesignation)
        {
            var empnameParameter = empname != null ?
                new ObjectParameter("empname", empname) :
                new ObjectParameter("empname", typeof(string));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("salary", salary) :
                new ObjectParameter("salary", typeof(int));
    
            var empDesignationParameter = empDesignation != null ?
                new ObjectParameter("empDesignation", empDesignation) :
                new ObjectParameter("empDesignation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_insertEmployeeExample2", empnameParameter, salaryParameter, empDesignationParameter);
        }
    }
}
